apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
  name: placeholder
contexts:
- context:
    cluster: placeholder
    user: placeholder
  name: placeholder
current-context: placeholder
kind: Config
preferences: {}
users:
- name: placeholder
  user:
    token: placeholder
